config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # root 'home#index'
  root 'events#index_Unauth'
  devise_for :users, controllers: { registrations: 'registrations' }

  # resources :speaker_events
  resources :speakers
  # resources :events #, only: [:new, :edit, :create, :destroy]
  # resources :bookings #, only: [:new, :edit, :create, :destroy]
  resources :events do
    resources :speakers, controller: 'speaker_events'
    resources :bookings do
      resources :payments
    end
    resources :payments
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/user.rb
# This Class handles operations related to User Record
class User < ApplicationRecord
  before_create :assign_uuid
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :events, dependent: :destroy
  has_many :bookings, dependent: :destroy
  has_many :speakers, dependent: :destroy

  enum role: { guest: 0, member: 1, admin: 2 }
  enum status: {
    active: 0,
    inactive: 1,
    blocked: 2,
  }


  validates :fname, presence: true, length: { minimum: 3, maximum: 50 }
  # validates :phone, presence: false, length: { minimum: 11, maximum: 15 }
  validates :phone, allow_blank: true, length: { minimum: 11, maximum: 15 }
  validates :role, presence: true, length: { minimum: 4, maximum: 7 }
  validates :credit_card, length: { minimum: 15, maximum: 16 }, allow_blank: true
  validates :credit_card_expiry, length: { is: 5 }, allow_blank: true

  validate :fullname_format

  def fullname_format
    return if fname.blank? || fname.split.size >= 2

    errors.add(:fname, 'Name must contain at least two names separated by a space')
  end

  private

  def assign_uuid
    self.id = SecureRandom.uuid
  end
end

app/views/entities/_form.html.erb
<!-- Other form fields -->
<%= f.hidden_field :event_id, value: @event.id %>
<div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control', required: true %>
</div>

<div class="form-group">
    <%= f.label :amount %>
    <%= f.text_field :amount, class: 'form-control' %>
</div>

<div class="form-group">
    <%= f.label :category_id %>
    <% Event.all.each do |event| %>
        <div class="form-check">
            <%= f.check_box :event_ids, { multiple: true }, event.id, nil %>
            <%= f.label :event_ids, event.name %>
        </div>
    <% end %>
</div>

<div class="form-group pt-2">
    <%= f.submit 'Save', class: 'btn btn-primary w-100' %>
</div>

app/views/entities/edit.html.erb
<div class="p-2 mt-4">
  <div class="row justify-content-center">
    <div class="col-md-12">
      <div class="card">
        <div class="card-header">
          Edit Booking
        </div>
        <div class="card-body">
          <%= form_for([@event, @booking]) do |f| %>
            <%= render 'form', booking: @booking, f: f %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/entities/index.html.erb
<div class="">
  <div class="mb-4 bg-primary d-flex text-center justify-content-between p-4 text-light">
    <%= link_to events_path, class: "pe-4 text-decoration-none text-light" do %>
      <i class="fas fa-arrow-left fe-2 float-start"></i>
    <% end %>
    <span><%= @event.name %></span>
    <span class='text-bold'><%= number_to_currency(@event.bookings.sum(:amount), unit: "$") %></span>

  </div>
  <div class="row gap-2 justify-content-center p-3 pt-0 mt-0 pb-5">
    <% @bookings.each do |booking| %>
      <div class="col-md-12 card p-0 text-secondary">
        <div class="d-flex">
          <div class="col-3 col-md-1">
            <img src=<%= @event.icon %> class='img-tumbnail'>
          </div>
          <div class="col-6 col-md-8">
            <div class="col-12">
              <%= booking.name %>
            </div>
            <div class="col-12 mt-4">
              <%= booking.created_at.strftime('%b %d %Y') %>
            </div>
          </div>
          <div class="col-3">
            <p class='text-bold text-dark text-end pe-1'><%= number_to_currency(booking.amount, unit: "$") %></p>
          </div>
        </div>
        <div class="p-1">
          <%= form_with(model: booking, url: event_booking_path(@event, booking), method: :delete, data: { confirm: 'Are you sure?' }, class: 'd-flex gap-2 justify-content-end') do |form| %>
            <%= link_to edit_event_booking_path(@event, booking), class: 'btn btn-sm btn-primary mr-2' do %>
              <i class="fas fa-edit"></i>
            <% end %>
              <%= form.button type: 'submit', class: 'btn btn-danger btn-sm' do %>
                <i class="fa fa-trash"></i>
              <% end %>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>
  <div class="text-center bottom-element w-100">
    <%= link_to "New Booking", new_event_booking_path(@event), class: "btn btn-success w-100" %>
  </div>

app/views/entities/new.html.erb
<div class="mb-4 bg-primary d-flex text-center justify-content-between p-4 text-light">
  <%= link_to event_bookings_path(@event), class: "pe-4 text-decoration-none text-light" do %>
    <i class="fas fa-arrow-left fe-2 float-start"></i>
  <% end %>
  <span><%= @event.name %></span>
  <span class='text-bold'><%= number_to_currency(@event.bookings.sum(:amount), unit: "$") %></span>

</div>

<div class="mt-4 p-2">
  <div class="row justify-content-center">
    <div class="col-md-12">
      <div class="card col-md-4 mx-auto">
        <div class="card-header">
          New Booking
        </div>
        <div class="card-body">
          <%= form_with(model: [@event, @booking], url: event_bookings_path(@event), method: :post) do |f| %>
            <%= render 'form', booking: @booking, f: f %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>