config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # root 'home#index'
  root 'events#index_Unauth'
  devise_for :users, controllers: { registrations: 'registrations' }

  # resources :speaker_events
  resources :speakers
  # resources :events #, only: [:new, :edit, :create, :destroy]
  # resources :bookings #, only: [:new, :edit, :create, :destroy]
  resources :events do
    resources :speakers, controller: 'speaker_events'
    resources :bookings do
      resources :payments
    end
    resources :payments
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/event.rb
# This Class handles operations related to Event
class Event < ApplicationRecord
  belongs_to :organizer, class_name: 'User', foreign_key: 'organizer_id'
  has_many :bookings
  has_many :speaker_events
  has_many :speakers, through: :speaker_events

  attr_accessor :hashes_input
  validate :validate_hashes

  def validate_hashes
    return unless hashes_input.present?

    options = ['Conference', 'Workshop', 'Seminar', 'Party']
    entered_values = hashes_input.split(',').map(&:strip)
    validated_values = (options & entered_values).join(',')

    # If you allow custom values, add them to the validated list
    custom_values = entered_values - options
    validated_values += ",#{custom_values.join(',')}" if custom_values.any?

    self.hashes = validated_values
  end

  enum status: {
    active: 0,
    inactive: 1,
    blocked: 2,
  }

  validates :title, presence: true, length: { minimum: 3, maximum: 150 }
  validates :datetime, presence: true
  validates :venue, presence: true, length: { minimum: 4, maximum: 150 }
  validates :details, presence: true, length: { minimum: 10, maximum: 2500 }
  validates :vip_price, presence: true, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 10000 }
  validates :regular_price, presence: true, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 10000 }
  validates :available_slot, presence: true, numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 100000 }
  validates :status, presence: true # , inclusion: { in: status }
end

app/controllers/events_controller.rb
# This controller handles operations related to Events.
# Events represent certain objects within the system.
# It handles CRUD operations for Events.
class EventsController < ApplicationController
  before_action :authenticate_user!, except: [:index_Unauth, :show]
  before_action :set_event, only: %i[edit update destroy]

  def index_Unauth
    @events = Event.where(status: :active).includes(:bookings)

    if params[:sort] == 'ancient'
      @events = @events.order(created_at: :asc)
    else # if params[:sort] == 'recent'
      @events = @events.order(created_at: :desc)
    end

    @event_booking_sums = {}
    @events.each do |event|
      @event_booking_sums[event.id] = event.bookings.sum(:amount)
    end
  end

  def index
    if current_user.admin?
      @events = Event.all.includes(:bookings)
    else
      # @events = current_user.events.where(status: :blocked).includes(:bookings)
      @events = current_user.events.where(status != blocked).includes(:bookings)
    end

    if params[:sort] == 'ancient'
      @events = @events.order(created_at: :asc)
    else # if params[:sort] == 'recent'
      @events = @events.order(created_at: :desc)
    end

    @event_booking_sums = {}
    @events.each do |event|
      @event_booking_sums[event.id] = event.bookings.sum(:amount)
    end
  end

  def show
    @events = Event.find(params[:id])
  end

  def new
    # @event = current_user.events.build
    @event = Event.new(organizer_id: current_user.id)
  end

  def edit
    # Renders edit form for specific event
  end

  def create
    # @event = current_user.events.build(event_params)
    @event = Event.new(event_params)
    @event.status = 0
    @event.organizer_id = current_user.id
    if @event.save
      # redirect_to events_path, notice: 'Event was successfully created.'
      redirect_to speaker_events_path(@event), notice: 'Event was successfully created.'
    else
      pp @event.errors.messages
      flash[:error] = @event.errors.full_messages.to_sentence
      render :new
    end
  end

  def update
    if @event.update(event_params)
      redirect_to events_path, notice: 'Event was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @event = Event.find(params[:id])
    if current_user == @event.user # Ensure the current user owns the event
      @event.bookings.destroy_all
      @event.destroy
      redirect_to events_path, notice: 'Event was successfully removed.'
    else
      redirect_to events_path, alert: "You don't have permission to remove this event."
    end
  end

  private

  def set_event
    @event = current_user.events.find(params[:id])
  end

  def event_params
    params.require(:event).permit(
      :title, :datetime, :venue, :details, :vip_price,
      :regular_price, :available_slot, :status, :hashes
    )
  end
end

app/helpers/events_helper.rb
# This Helper handles operations related to Events
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_for(event) do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control', required: true %>
  </div>

  <div class="form-group">
    <%= f.label :datetime %>
    <%= f.datetime_local_field :datetime, class: 'form-control', required: true %>
  </div>

  <div class="form-group">
    <%= f.label :venue %>
    <%= f.text_field :venue, class: 'form-control', required: true %>
  </div>

  <div class="form-group">
    <%= f.label :details %>
    <%= f.text_area :details, class: 'form-control', required: true %>
  </div>

  <div class="form-group">
    <%= f.label :vip_price %>
    <%= f.number_field :vip_price, class: 'form-control', step: '0.01', required: true %>
  </div>

  <div class="form-group">
    <%= f.label :regular_price %>
    <%= f.number_field :regular_price, class: 'form-control', step: '0.01', required: true %>
  </div>

  <div class="form-group">
    <%= f.label :available_slot %>
    <%= f.number_field :available_slot, class: 'form-control', required: true %>
  </div>

  <div class="form-group">
    <label>
      Tag(s)
    </label>
    <!-- Hidden field to store the validated hashes -->
    <%= f.text_field :hashes, disabled: true, hidden: true %>
    <div class="tags-input"> 
        <ul id="tags"></ul> 
        <input type="text" id="input-tag", class='form-control' 
            placeholder="Add a tag" /> 
    </div> 
  </div>

  <div class="form-group pt-2">
    <%= f.submit 'Save', class: 'btn btn-primary w-100' %>
  </div>
<% end %>

<script>
  // Get the tags and input elements from the DOM
  const tags = document.getElementById('tags');
  const input = document.getElementById('input-tag');
  const hiddenHashesField = document.querySelector('input[name="event[hashes]"]');

  // Initialize an array to store tags
  const tagArray = [];

  // Add an event listener for keydown on the input element
  input.addEventListener('keydown', function (event) {

    // Check if the key pressed is 'Enter'
    if (event.key === 'Enter') {

      // Prevent the default action of the keypress event (submitting the form)
      event.preventDefault();

      // Get the tag value from the input and trim whitespace
      const tagValue = input.value.trim();

      // Check if the tag is not empty and is not already in the array
      if (tagValue && !tagArray.includes(tagValue)) {

        // Add the tag to the array
        tagArray.push(tagValue);

        // Create a new list item element for the tag
        const tag = document.createElement('li');

        // Set the text content of the tag to the input value
        tag.innerText = tagValue;

        // Append the tag to the tags list
        tags.appendChild(tag);

        // Update the hidden hashes field with the comma-separated tags
        hiddenHashesField.value = tagArray.join(',');
      }

      // Clear the input element's value
      input.value = '';
    }
  });
</script>

app/views/events/edit.html.erb
<div class="p-2 mt-4">
  <div class="row justify-content-center">
    <div class="col-md-12">
      <div class="card">
        <div class="card-header">
          Edit Event
        </div>
        <div class="card-body">
          <%= render 'form', event: @event %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/events/index.html.erb
<div class="">
  <div class="row mb-4 text-end justify-content-end bg-primary p-2">
    <%= link_to 'Most Recent', events_path(sort: 'recent'), class: 'text-decoration-none text-light mw-100' %>
    <%= link_to 'Most Ancient', events_path(sort: 'ancient'), class: 'text-decoration-none text-light mw-100' %>
  </div>

  <div class="row gap-2 justify-content-center p-3 pt-0 mt-0 pb-5">
    <% @events.each do |event| %>
      <div class="col-md-12 card p-0">
        <%= link_to event_bookings_path(event), class: 'text-decoration-none text-secondary' do %>
          <div class="d-flex">
            <div class="col-3 col-md-1">
              <img src=<%= event.icon %> class='img-tumbnail'>
            </div>
            <div class="col-6 col-md-8">
              <div class="col-12">
                <%= event.name %>
              </div>
              <div class="col-12 mt-4">
                <%= event.created_at.strftime('%b %d %Y') %>
              </div>
            </div>
            <div class="col-3">
              <% sum = @event_booking_sums[event.id] || 0 %>
              <p class='text-bold text-dark text-end pe-1'><%= number_to_currency(sum, unit: "$") %></p>
            </div>
          </div>
          <div class="p-1">
            <%= form_with(model: event, url: event_path(event), method: :delete, data: { confirm: 'Are you sure?' }, class: 'd-flex gap-2 justify-content-end') do |form| %>
              <%= link_to edit_event_path(event), class: 'btn btn-sm btn-primary mr-2' do %>
                <i class="fas fa-edit"></i>
              <% end %>
              <%= form.button type: 'submit', class: 'btn btn-danger btn-sm' do %>
                <i class="fa fa-trash"></i>
              <% end %>
            <% end %>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>
  
  <div class="bottom-element w-100">
    <%= link_to "Add Event", new_event_path(), class: "btn btn-success w-100" %>
  </div>

app/views/events/index_Unauth.html.erb
<div class="">
  <div class="row mb-4 text-end justify-content-end bg-primary p-2">
    <%= link_to 'Most Recent', root_path(sort: 'recent'), class: 'text-decoration-none text-light mw-100' %>
    <%= link_to 'Most Ancient', root_path(sort: 'ancient'), class: 'text-decoration-none text-light mw-100' %>
  </div>

  <div class="row gap-2 justify-content-center p-3 pt-0 mt-0 pb-5">
    <% @events.each do |event| %>
      <div class="col-md-12 card p-0">
        <%= link_to event_bookings_path(event), class: 'text-decoration-none text-secondary' do %>
          <div class="d-flex">
            <div class="col-3 col-md-1">
              <img src=<%= event.icon %> class='img-tumbnail'>
            </div>
            <div class="col-6 col-md-8">
              <div class="col-12">
                <%= event.name %>
              </div>
              <div class="col-12 mt-4">
                <%= event.created_at.strftime('%b %d %Y') %>
              </div>
            </div>
            <div class="col-3">
              <% sum = @event_booking_sums[event.id] || 0 %>
              <p class='text-bold text-dark text-end pe-1'><%= number_to_currency(sum, unit: "$") %></p>
            </div>
          </div>
          <div class="p-1">
            <%= form_with(model: event, url: event_path(event), method: :delete, data: { confirm: 'Are you sure?' }, class: 'd-flex gap-2 justify-content-end') do |form| %>
              <%= link_to edit_event_path(event), class: 'btn btn-sm btn-primary mr-2' do %>
                <i class="fas fa-edit"></i>
              <% end %>
              <%= form.button type: 'submit', class: 'btn btn-danger btn-sm' do %>
                <i class="fa fa-trash"></i>
              <% end %>
            <% end %>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>
  
  <div class="bottom-element w-100">
    <%= link_to "Add Event", new_event_path(), class: "btn btn-success w-100" %>
  </div>

app/views/events/new.html.erb
<div class="mb-4 bg-primary d-flex text-center justify-content-between p-4 text-light">
  <%= link_to events_path, class: "pe-4 text-decoration-none text-light" do %>
    <i class="fas fa-arrow-left fe-2 float-start"></i>
  <% end %>
  <span>Add a Category</span>
  <span></span>

</div>

<div class="p-2 mt-4">
  <div class="row justify-content-center">
    <div class="col-md-12">
      <div class="card col-md-4 mx-auto">
        <div class="card-header">
          New Event
        </div>
        <div class="card-body">
          <%= render 'form', event: @event %>
        </div>
      </div>
    </div>
  </div>
</div>