config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # root 'home#index'
  root 'events#index_Unauth'
  devise_for :users, controllers: { registrations: 'registrations' }

  # resources :speaker_events
  resources :speakers
  # resources :events #, only: [:new, :edit, :create, :destroy]
  # resources :bookings #, only: [:new, :edit, :create, :destroy]
  resources :events do
    resources :speakers, controller: 'speaker_events'
    resources :bookings do
      resources :payments
    end
    resources :payments
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ticket manager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css' %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <script src="https://cdn.jsdelivr.net/npm/@rails/ujs/dist/rails-ujs.min.js"></script>

    <!-- Add jQuery library -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

    <!-- Add jQuery UI library -->
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

    <!-- Select2 CSS -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.1.0/css/select2.min.css" rel="stylesheet" />

    <!-- Select2 JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.1.0/js/select2.min.js"></script>



    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <div class="container">
          <a class="navbar-brand" href="/">Ticket manager</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <%= link_to 'Home', root_path, class: "nav-link active"  %>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Event
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <li><%= link_to 'Events', events_path, class: "dropdown-item" %></li>
                  <% if user_signed_in? %> <!-- Check if the user is signed in -->
                    <li><%= link_to 'New Event', new_event_path, class: "dropdown-item" %></li>
                  <% end %>
                </ul>
              </li>
              <%
=begin%>
 <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown2" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Booking
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown2">
                  <li><%= link_to 'Bookings', bookings_path, class: "dropdown-item" %></li>
                  <% if user_signed_in? %> <!-- Check if the user is signed in -->
                    <li><%= link_to 'New Booking', new_booking_path, class: "dropdown-item" %></li>
                  <% end %>
                </ul>
              </li> 
<%
=end%>
              <% if current_user.present? %> <!-- Check if the user is present (logged in) -->
                <li class="nav-item">
                 <li class="nav-item"><%= button_to 'Logout', destroy_user_session_path, method: :delete, class: "nav-link logout--btn" %></li>
                </li>
              <% else %>
                <li class="nav-item"><%= link_to 'Login', new_user_session_path, class: "nav-link" %></li>
                <li class="nav-item"><%= link_to 'Sign Up', new_user_registration_path, class: "nav-link" %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <div class=''>
      <% if flash[:notice] %>
        <div class="alert alert-success">
          <%= flash[:notice] %>
        </div>
      <% end %>

      <% if flash[:error] %>
        <div class="alert alert-danger">
          <%= flash[:error] %>
        </div>
      <% end %>

      <p class="notice m-0 p-0"><%= notice %></p>
      <%
=begin%>
 <%= render 'shared/header' %>  
<%
=end%>
      <%= yield %>
    </div>
  </body>
</html>